# Generated by Django 3.1 on 2020-08-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddinglist', '0002_auto_20200808_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding_list',
            name='product_payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
